name: Publish Release
on:
  push:
    tags:
      - "v*.*.*"

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release-carthage:
    name: Release for Carthage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check-out source
        # TODO: Create Berbix.json
      - name: Create Carthage Zip
        run: |
          mkdir -p Carthage/Build/iOS/
          cp -r Berbix.xcframework Carthage/Build/iOS
          zip -r Berbix.xcframework.zip Carthage
      - name: Add Carthage Zip to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ github.ref_name }}
          files: Berbix.xcframework.zip
          draft: true
  release-cocoapods:
    name: Release for CocoaPods
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Check-out source
      - name: Lint & Deploy Podspec
        run: |
          pod repo add berbix https://github.com/berbix/berbix-ios-distribution.git
          pod lib lint --verbose
          #pod repo push berbix Berbix.podspec
