name: Publish Release
on:
  push:
    tags:
      - "v*.*.*"

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  RELEASE_NAME: ${{ github.ref_name }}

jobs:
  release-carthage:
    name: Release for Carthage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check-out source
      - name: Create Carthage Zip
        run: |
          mkdir -p Carthage/Build/iOS/
          cp -r Berbix.xcframework Carthage/Build/iOS
          zip -r Berbix.xcframework.zip Carthage
      - name: Add Carthage Zip to GitHub Release
        id: carthage
        uses: softprops/action-gh-release@master
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ github.ref_name }}
          files: |
            Berbix.xcframework.zip
          draft: true
      - name: Create Berbix.json
        env:
          DOWNLOAD_URL: ${{ fromJSON(steps.carthage.outputs.assets)[0].browser_download_url }}
        run: |
          printf '{ "%s": "%s" }' "${RELEASE_NAME:1}" "$DOWNLOAD_URL" > Berbix.json
          cat Berbix.json
      - name: Add Berbix.json to GitHub Release
        uses: softprops/action-gh-release@master
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ github.ref_name }}
          files: |
            Berbix.json
          draft: true
      
  release-cocoapods:
    name: Release for CocoaPods
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Check-out source
      - name: Lint & Deploy Podspec
        run: |
          pod repo add berbix https://github.com/berbix/berbix-ios-distribution.git
          pod lib lint --verbose
          #pod repo push berbix Berbix.podspec
