name: Tag Release on Merge
on:
  release:
    types: [created]
  pull_request: 
    types: [closed]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  RELEASE_NAME: ${{ github.ref_name }}

jobs:
  tag-version:
    # if: github.event.pull_request.merged == 'true' && github.event.pull_request.labels[0] == 'release'
    name: Add Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check-out source
      - name: Create Release from Merge
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          prerelease: true
